# encoding: utf-8
require 'rubygems'
require 'rake'

begin
  require 'jeweler'
  Jeweler::Tasks.new do |gem|
    gem.name = "cuke4duke"
    gem.summary = %Q{JVM support for Cucumber}
    gem.description = %Q{Write Cucumber Step Definitions in Java, Scala, Groovy, Rhino Javascript, Clojure or Ioke}
    gem.email = "cukes@googlegroups.com"
    gem.homepage = "http://cukes.info"
    gem.authors = ["Aslak Hellesøy"]
    gem.executables = ["cuke4duke"]
    gem.files = FileList['VERSION', 'lib/cuke4duke.jar', 'bin/cuke4duke']
    gem.test_files = []

    gem.add_dependency 'cucumber', '>= 0.7.0.beta.1'
    gem.platform = 'java'
  end

  Jeweler::GemcutterTasks.new
rescue LoadError
  puts "Jeweler (or a dependency) not available. Install it with: sudo gem install jeweler"
end
