language: android
jdk: oraclejdk8
sudo: false

cache:
  directories:
  - "$HOME/.m2"

before_cache:
- rm -rf $HOME/.m2/repository/io/cucumber

android:
  components:
  - tools
  - platform-tools
  - tools
  - build-tools-26.0.0
  - android-21
  - sys-img-armeabi-v7a-android-21

before_install:
  - echo no | android create avd --force -n test -t android-21 --abi armeabi-v7a
  - emulator -avd test -no-skin -no-audio -no-window &

install:
  - mvn -q install --also-make --projects android,picocontainer -DskipTests=true
    -Dmaven.javadoc.skip=true

before_script:
  - android-wait-for-emulator

script:
  - mvn install --activate-profiles android-examples --projects examples/android
    --also-make-dependents -Dandroid.device=test
