version: '2'
services:
     
  maven-app-build:
     user: "997:994"
     image: maven:3.5-jdk-8
     volumes:
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
      - "${JENKINS_HOME}:${JENKINS_HOME}:rw"
      - "${WORKSPACE}:${WORKSPACE}:rw"
     
  maven-app-image:
     build:
       context: .
       dockerfile: Dockefile.develop
     image: rcx-java-maven:latest

  maven-app-image-docker:
     build: .
     image: rcx-java-maven-docker:latest
