desc 'Generate i18n annotations'
task :generate do
  require 'gherkin/i18n'
  require 'erb'

  java = ERB.new(IO.read(File.dirname(__FILE__) + '/src/main/code_generator/I18n.java.erb'), nil, '-')
  File.open(File.dirname(__FILE__) + '/src/main/java/cucumber/annotation/I18n.java', 'wb') do |io|
    io.write(<<-HEADER)
package cucumber.annotation;

import cucumber.runtime.java.CucumberAnnotation;
import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

public interface I18n {

    HEADER
    Gherkin::I18n.all.each do |i18n|
      io.write(java.result(binding))
    end

    io.write("}")
  end
end
