name: Cucumber CI

on:
  push:
  pull_request:
    branches:
      - main
      - v4.x.x
      - v5.x.x
      - v6.x.x


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - uses:
          AdoptOpenJDK/install-jdk@v1
        with:
          version: '11'

      - name: install dependencies
        run: mvn install -DskipTests=true -DskipITs=true -Darchetype.test.skip=true -Dmaven.javadoc.skip=true -B -V --toolchains .github/workflows/.toolchains.xml

      - name: test (Semver check)
        run: mvn verify -Pcheck-semantic-version -DskipTests=true -DskipITs=true -Darchetype.test.skip=true --toolchains .github/workflows/.toolchains.xml
        env:
          CHECK_SEMANTIC_VERSION: true

      - name: test
        run: mvn verify -P-spotless-apply --toolchains .github/workflows/.toolchains.xml
        env:
          VERIFY: true

      - name: test (coverage)
        run: mvn jacoco:prepare-agent verify jacoco:report -DdryRun=true --toolchains .github/workflows/.toolchains.xml
        env:
          COVERAGE: true

      - name: javadoc
        run: mvn javadoc:jar --toolchains .github/workflows/.toolchains.xml
        env:
          JAVADOC: true
