name: Parse changelog

on:
  push:

jobs:
  changelog:
    name: "Changelog"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cucumber/action-changelog@v1.3
        id: changelog
        with:
          args: latest
      - run: echo ${{ steps.changelog.outputs.result }}
