name: Release on GitHub

on:
  push:
    branches: [release/*]

jobs:
  pre-release-check:
    uses: cucumber/.github/.github/workflows/prerelease-checks.yml@main

  create-github-release:
    name: Create GitHub Release and Git tag
    runs-on: ubuntu-latest
    needs: [pre-release-check]
    environment: Release
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2
      - uses: cucumber/action-create-github-release@v1.1.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
