name: Release Maven

permissions: { }

on:
  push:
    branches: [release/*]

jobs:
  publish-mvn:
    name: Publish Maven Package
    runs-on: ubuntu-latest
    environment: Release
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false
      - uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.2.0
        with:
          distribution: 'temurin'
          java-version: '21'
      - uses: cucumber/action-publish-mvn@252601e47a5d699c325d1f046199a4d6f2c7b9db # v3.0.1
        with:
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg-passphrase: ${{ secrets.GPG_PASSPHRASE }}
          nexus-username: ${{ secrets.SONATYPE_USERNAME }}
          nexus-password: ${{ secrets.SONATYPE_PASSWORD }}
