name: Release GitHub

on:
  push:
    branches: [release/*]

jobs:
  create-github-release:
    name: Create GitHub Release and Git tag
    runs-on: ubuntu-latest
    environment: Release
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4
      - uses: cucumber/action-create-github-release@v1.1.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
