name: Test Java
  
permissions: { }  

on:
  pull_request:
    branches:
      - '**'
  push:
    branches:
      - main
      - v4.x.x
      - v5.x.x
      - v6.x.x
      - v7.x.x
      - renovate/**

jobs:
  build:
    strategy:
      fail-fast: true
      matrix:
        os:
          - ubuntu-latest
        version:
          - 21
          - 25
        include:
          - os: windows-latest
            version: 21

    name: 'Build Java ${{ matrix.version }} - ${{ matrix.os }}'
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - uses: actions/setup-java@ad2b38190b15e4d6bdf0c97fb4fca8412226d287 # v5.3.0
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.version }}
          cache: 'maven'
      - name: Install dependencies
        run: mvn install -Pinclude-extra-modules -DskipTests=true -DskipITs=true -D"archetype.test.skip=true" -D"maven.javadoc.skip=true" --batch-mode -D"style.color=always" --show-version
      - name: Test
        run: mvn verify -Pinclude-extra-modules -D"style.color=always"

  javadoc:
    name: 'Javadoc'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - uses: actions/setup-java@ad2b38190b15e4d6bdf0c97fb4fca8412226d287 # v5.3.0
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'
      - name: Install dependencies
        run: mvn install -DskipTests=true -DskipITs=true -Darchetype.test.skip=true -Dmaven.javadoc.skip=true --batch-mode -Dstyle.color=always --show-version
      - name: Javadoc
        run: mvn javadoc:jar -Dstyle.color=always

  semver:
    name: 'Semver'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - uses: actions/setup-java@ad2b38190b15e4d6bdf0c97fb4fca8412226d287 # v5.3.0
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'
      - name: Install dependencies
        run: mvn install -DskipTests=true -DskipITs=true -Darchetype.test.skip=true -Dmaven.javadoc.skip=true --batch-mode -Dstyle.color=always --show-version
      - name: Test (Semver check)
        run: mvn verify -Pcheck-semantic-version -DskipTests=true -DskipITs=true -Darchetype.test.skip=true -Dstyle.color=always
